name: Bot Retry Workflow

on:
  workflow_run:
    workflows: ["Run job when failed"]
    types: [completed]

jobs:
  on-failure:
    runs-on: ubuntu-latest
    # Retry 1 times
    if: ${{ github.event.workflow_run.conclusion == 'failure' && github.event.workflow_run.run_attempt < 2 }}
    steps:
    - run: |
        echo "run_attempt: ${{ github.event.workflow_run.run_attempt  }}"
        gh run rerun ${{ github.event.workflow_run.id }}
        echo "${{ toJSON(github.event.workflow_run)  }}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_REPO: ${{ github.event.repository.full_name }}

    # - if: ${{ github.event.workflow_run.run_attempt < 2 }}