name: Bot Retry Workflow

on:
  workflow_run:
    workflows: ["Run job when failed"]
    types: [completed]

jobs:
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
    - if: ${{ github.event.workflow_run.run_attempt <= 2 }}
      run: |
        echo "run_attempt: ${{ github.event.workflow_run.run_attempt  }}"
        gh run rerun ${{ github.event.workflow_run.id }} --repo ${{ github.event.repository.full_name }}
        echo "${{ toJSON(github.event.workflow_run)  }}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}