name: Bot Retry Workflow

on:
  workflow_run:
    workflows: ["Run job when failed"]
    types: [completed]

jobs:
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
    - run: |
        echo "${{ toJSON(github.event.workflow_run) }}"

# gh run rerun 1632791743 --repo my-wrm/github-action-demo