name: Debug

on:
  workflow_dispatch:
    inputs:
      deploy_cards:
        description: Note
      run_db_migration:
        type: boolean
        default: "true"
        description: Run DB Migration

jobs:

  build:
    if: ${{ github.event.inputs.run_db_migration == "true" }}
    runs-on: ubuntu-latest
    steps:
    - name: Send greeting
      run: |
        echo "::notice title=Deployment Note::${{ github.event.inputs.deploy_cards }}"
