name: Debug

on:
  workflow_dispatch:
    inputs:
      note:
        description: Note

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Send greeting
      run: |
        echo "::notice title=Deployment Note::${{ github.event.inputs.note }}"
