name: Debug Yahhhhhhhhh

on:
  workflow_dispatch:
    inputs:
      deploy_cards:
        description: Note
        
# env:
#   github_workflow: $GITHUB_WORKFLOW
#   github_workflow_url: "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"

jobs:
  build:
    if: always()
    runs-on: ubuntu-latest
    steps:
    - name: Send greeting workflow_dispatch
      run: |
        echo "${{ env.github_workflow }} ${{ env.github_workflow_url }}"
    - name: Send greeting 
      run: |
        echo "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
        
  # notify:
  #   if: success()
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Send custom JSON data to Slack workflow
  #     id: slack
  #     uses: slackapi/slack-github-action@v1.18.0
  #     with:
  #       # For posting a rich message using Block Kit
  #       payload: |
  #         {
  #           "attachments": [
  #             {
  #               "mrkdwn_in": ["text"],
  #                 "color": "#36a64f",
  #                 "pretext": "Optional pre-text that appears above the attachment block",
  #                 "author_name": "author_name",
  #                 "author_link": "http://flickr.com/bobby/",
  #                 "author_icon": "https://placeimg.com/16/16/people",
  #                 "title": "title",
  #                 "title_link": "https://api.slack.com/",
  #                 "text": "Optional `text` that appears within the attachment",
  #                 "fields": [
  #                     {
  #                         "title": "A field's title",
  #                         "value": "This field's value",
  #                         "short": false
  #                     },
  #                     {
  #                         "title": "A short field's title",
  #                         "value": "A short field's value",
  #                         "short": true
  #                     },
  #                     {
  #                         "title": "A second short field's title",
  #                         "value": "A second short field's value",
  #                         "short": true
  #                     }
  #                 ],
  #                 "thumb_url": "http://placekitten.com/g/200/200",
  #                 "footer": "footer",
  #                 "footer_icon": "https://platform.slack-edge.com/img/default_application_icon.png",
  #                 "ts": 123456789
  #             }
  #           ]
  #         }
  #     env:
  #       SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  #       SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK


#     - name: Set COMMIT_MESSAGE
#       run: echo "COMMIT_MESSAGE=${{ github.event.head_commit.message }}" | tr '\n' ' ' >> $GITHUB_ENV
      
#     - name: Slack Notification on SUCCESS
#       uses: tokorom/action-slack-incoming-webhook@main
#       env:
#         INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
#       with:
#         text: Successfully automated deployment.
#         attachments: |
#           [
#             {
#               "color": "good",
#               "author_name": "${{ github.actor }}",
#               "author_icon": "${{ github.event.sender.avatar_url }}",
#               "fields": [
#                 {
#                   "title": "Commit Message",
#                   "value": "${{ env.COMMIT_MESSAGE }}"
#                 },
#                 {
#                   "title": "GitHub Actions URL",
#                   "value": "${{ github.event.repository.url }}/actions/runs/${{ github.run_id }}"
#                 },
#                 {
#                   "title": "Compare URL",
#                   "value": "${{ github.event.compare }}"
#                 }
#               ]
#             }
#           ]