name: Debug Yahhhhhhhhh

on:
  workflow_dispatch:
    inputs:
      deploy_cards:
        description: Note
        
env:
  github_workflow: $GITHUB_WORKFLOW
  github_workflow_url: "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"

jobs:

  build:
    if: always()
    runs-on: ubuntu-latest
    steps:
    - name: Send greeting workflow_dispatch
      run: |
        echo "$GITHUB_WORKFLOW"
    - name: Send greeting 
      run: |
        echo "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
        
        
