name: Demo Matrix

on:
  push:
  workflow_dispatch:
  
env:
  template: password_{0}

jobs:
  pre:
    runs-on: ubuntu-latest
    steps:
      - id: main
        run: |
          echo "::set-output name=password_cat::catcat"
          echo "::set-output name=password_dog::dogdog"
        
  build:
    runs-on: 'ubuntu-latest'
    needs: pre
    strategy:
      matrix:
        animal: 
          - cat
          - dog

    steps:

    - name: test matrix value
      run: |
        Write-Host "Hello ${{ needs.pre.outputs[format(env.template,matrix.animal)]  }}"

