name: Demo Matrix

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: 'windows-latest'
    strategy:
      matrix:
        test-path: 
          - path1
          - path2

    steps:

    - name: test matrix value
      run: |
        Write-Host "Hello ${{ matrix.test-path }}"

