# https://github.com/marketplace/actions/validate-json
# https://stackoverflow.com/a/61919791
name: deploy from json v2

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      deployment-matrix: ${{ steps.export-deployment-matrix.outputs.deployment-matrix }}
    steps:
      - uses: actions/checkout@v2
      - name: Export deployment matrix
        id: export-deployment-matrix
        uses: mildronize/import-json-action@v0.0.1
        with:
          conifg-path: ./.github/workflows/config.json

  deploy:
    runs-on: ubuntu-latest
    needs: [ build ]
    strategy:
      matrix:
        server: ${{ fromJson(needs.build.outputs.deployment-matrix) }}
        
    steps:
    - name: Test Deploy
      run: |
        echo "${{ matrix.server.name }}"
    - name: Test Deploy IP
      run: |
        echo "${{ matrix.server.ip }}"
      
