
name: Debug

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Export deployment matrix
        id: export-deployment-matrix
        run: |
          JSON="$(cat ./deployment-config.json)"
          JSON="${JSON//'%'/'%25'}"
          JSON="${JSON//$'\n'/'%0A'}"
          JSON="${JSON//$'\r'/'%0D'}"
          echo "::set-output name=deployment-matrix::$JSON"
          
  deploy:
    name: "${{ matrix.server.name }}: Deploy"
    runs-on: ubuntu-latest
    needs: [ build ]
    strategy:
      matrix:
        server: ${{ fromJson(needs.build.outputs.deployment-matrix) }}
      
    
