name: Fallback Jobs

on:
  push:

jobs:
  step1:
    runs-on: 'ubuntu-latest'
    steps:
      - run: |
          echo "Renaming... "
          echo "Copying....."
          
  step1-on-success:
    needs: step1
    if: success()
    runs-on: 'ubuntu-latest'
    steps:
      - run: |
          echo "deleting... "
          
  step1-on-fail:
    needs: step1
    if: failure()
    runs-on: 'ubuntu-latest'
    steps:
      - run: |
          echo "reverting... "
