
name: Get Yaml Value

on:
  push:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: CumulusDS/get-yaml-paths-action@v0.1.0
        with:
          file: file.yml
          bar: foo.bar
          providerStage: provider.stage
