name: hide secret
on: 
  push:

env: 
  template: My_template_{0}

jobs:
  bash-example:
#     strategy:
#       matrix:
#         include:
#           - env_name: Dev_API
#           - env_name: Test_API
        
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Mask Password
        id: mark_password
        run: |
          secret=`cat "README.md"`
          echo "::add-mask::$secret"
          echo "::set-output name=password::$secret"
      - run: echo "${{ steps.mark_password.outputs.password }}"
