name: hide secret
on: 
  push:

env: 
  template: My_template_{0}

jobs:
  bash-example:
    strategy:
      matrix:
        id: [1,2,3]
        
    runs-on: ubuntu-latest
    steps:
      - name: bash-version
        run: echo "$HELLO"
        env: 
          HELLO: ${{ format(env.template, matrix.id }}
