name: hide secret
on: 
  push:

env: 
  template: My_template_{0}

jobs:
  bash-example:
#     strategy:
#       matrix:
#         include:
#           - env_name: Dev_API
#           - env_name: Test_API
        
    runs-on: ubuntu-latest
    steps:
      - name: Mask Password
        id: mark_password
        run: |
          echo
          echo "::add-mask::test"
          echo "::set-output name=password::test"
      - run: echo "${{ steps.mark_password.outputs.password }}"
#       - name: bash-version
#         run: echo "${{ format(env.template, secrets.MY_SECRET) }}"
