name: hide secret
on: 
  push:

env: 
  template: My_template_{0}

jobs:
  bash-example:
    strategy:
      matrix:
        include:
          - env_name: Dev_API
          - env_name: Test_API
        
    runs-on: ubuntu-latest
    steps:
      - name: bash-version
        run: echo "$HELLO"
        env: 
          HELLO: ${{ format(env.template, matrix.env_name }}
